<?php

$cbz_cat_text = 'Intently sniff hand hopped up on goofballs so chew iPad power cord and chew foot, claw drapes hate dog find something else more interesting. Cat snacks hide when guests come over and use lap as chair but stick butt in face, but lick butt chew foot yet give attitude. Behind the couch burrow under covers but why must they do that. Flop over. Intently stare at the same spot hate dog stand in front of the computer screen inspect anything brought into the house nap all day and lick butt. Need to chase tail leave dead animals as gifts flop over so chase imaginary bugs and chew iPad power cord climb leg so nap all day. Behind the couch missing until dinner time. Attack feet intently stare at the same spot stare at ceiling stare at ceiling. Stretch chew foot for cat snacks cat snacks. Hunt anything that moves flop over or sleep on keyboard leave dead animals as gifts attack feet. Chew iPad power cord destroy couch, for find something else more interesting or find something else more interesting yet chase imaginary bugs missing until dinner time cat snacks. Stare at ceiling under the bed for hopped up on goofballs chase imaginary bugs intrigued by the shower for chase imaginary bugs. Use lap as chair. Stare at ceiling hunt anything that moves but why must they do that. Under the bed leave dead animals as gifts. Stand in front of the computer screen cat snacks behind the couch or mark territory need to chase tail attack feet or attack feet. 

Stare at ceiling run in circles for cat snacks but make muffins give attitude. Run in circles leave hair everywhere and stick butt in face or hopped up on goofballs. Find something else more interesting sweet beast under the bed hate dog yet sleep on keyboard yet rub face on everything. Play time need to chase tail sun bathe chase mice yet mark territory why must they do that. Leave hair everywhere intrigued by the shower for burrow under covers sun bathe make muffins so attack feet. Attack feet play time and shake treat bag mark territory, or all of a sudden go crazy destroy couch rub face on everything. Use lap as chair hate dog leave dead animals as gifts for shake treat bag make muffins swat at dog. Leave hair everywhere sun bathe climb leg stare at ceiling. Stand in front of the computer screen throwup on your pillow for sun bathe. Chase mice swat at dog stand in front of the computer screen. Give attitude stick butt in face or hate dog. Climb leg claw drapes, swat at dog hide when guests come over yet rub face on everything. Shake treat bag. Attack feet give attitude climb leg lick butt for find something else more interesting yet use lap as chair. Chew iPad power cord inspect anything brought into the house for find something else more interesting. Claw drapes chew foot attack feet missing until dinner time, shake treat bag. Swat at dog sun bathe for intently sniff hand but hide when guests come over for claw drapes but rub face on everything. Play time hate dog shake treat bag why must they do that rub face on everything. Burrow under covers. Inspect anything brought into the house hunt anything that moves, and leave hair everywhere mark territory all of a sudden go crazy, or hide when guests come over. Mark territory mark territory throwup on your pillow leave hair everywhere for leave hair everywhere use lap as chair. Why must they do that stretch. Use lap as chair destroy couch. 

Sun bathe. Burrow under covers. Need to chase tail inspect anything brought into the house intently stare at the same spot cat snacks. Give attitude claw drapes climb leg yet throwup on your pillow. Leave dead animals as gifts. Nap all day rub face on everything but need to chase tail and find something else more interesting. Hide when guests come over. Chase imaginary bugs behind the couch, and chew foot but sweet beast. Leave hair everywhere run in circles hide when guests come over for sweet beast so throwup on your pillow. Attack feet sun bathe and stare at ceiling for claw drapes and sleep on keyboard. Sleep on keyboard stand in front of the computer screen and nap all day or intently sniff hand for give attitude so flop over stand in front of the computer screen. Shake treat bag run in circles for intently stare at the same spot for sweet beast. Destroy couch. ';

$cbz_bacon_text = 'Bacon ipsum dolor sit amet boudin spare ribs tenderloin capicola sausage, t-bone hamburger. Capicola tail shank pork belly, beef ham hock bresaola jowl short loin cow salami pork loin. Kielbasa salami t-bone, boudin rump chicken jerky ball tip venison. Chicken ground round ham hock brisket pork loin chuck. Meatloaf beef ribs pancetta ribeye shank drumstick salami pork chop pork pig prosciutto kielbasa. Leberkas chuck hamburger, tri-tip meatloaf ham andouille ground round pork belly chicken doner biltong.

Boudin turkey swine short ribs ball tip spare ribs pork ham pastrami bacon shank meatloaf. Venison boudin frankfurter salami ribeye pork pig jowl biltong cow beef ribs. Swine spare ribs biltong brisket turkey pork loin, flank venison kielbasa drumstick. Spare ribs tail pork belly, tongue shank t-bone kielbasa pork bresaola rump. Pork chop corned beef ribeye, bresaola brisket meatloaf frankfurter drumstick bacon beef sausage swine hamburger shankle pork. Venison ham hock shoulder, shank ball tip beef ribs hamburger rump meatloaf t-bone meatball short ribs prosciutto boudin.

Jowl biltong meatloaf, fatback beef chicken frankfurter sirloin chuck. Venison pork chop pancetta sausage. Tri-tip rump shoulder, corned beef shank prosciutto short loin salami boudin flank jerky capicola fatback ground round. Chicken sirloin pork venison bresaola salami, leberkas prosciutto pork loin sausage cow beef. Fatback ground round beef tenderloin ribeye sausage pork shankle rump chuck. Chicken flank sirloin boudin prosciutto ribeye rump pork biltong.';

$cbz_zombie_text = 'Zombie ipsum reversus ab viral inferno, nam rick grimes malum cerebro. De carne lumbering animata corpora quaeritis. Summus brains sit, morbo vel maleficia? De apocalypsi gorger omero undead survivor dictum mauris. Hi mindless mortuis soulless creaturas, imo evil stalking monstra adventus resi dentevil vultus comedat cerebella viventium. Qui animated corpse, cricket bat max brucks terribilem incessu zomby. The voodoo sacerdos flesh eater, suscitat mortuos comedere carnem virus. Zonbi tattered for solum oculi eorum defunctis go lum cerebro. Nescio brains an Undead zombies. Sicut malus putrid voodoo horror. Nigh tofth eliv ingdead.

Cum horribilem walking dead resurgere de crazed sepulcris creaturis, zombie sicut de grave feeding iride et serpens. Pestilentia, shaun ofthe dead scythe animated corpses ipsa screams. Pestilentia est plague haec decaying ambulabat mortuos. Sicut zeder apathetic malus voodoo. Aenean a dolor plan et terror soulless vulnerum contagium accedunt, mortui iam vivam unlife. Qui tardius moveri, brid eof reanimator sed in magna copia sint terribiles undeath legionis. Alii missing oculis aliorum sicut serpere crabs nostram. Putridi braindead odores kill and infect, aere implent left four dead.

Lucio fulci tremor est dark vivos magna. Expansis creepy arm yof darkness ulnis witchcraft missing carnem armis Kirkman Moore and Adlard caeruleum in locis. Romero morbo Congress amarus in auras. Nihil horum sagittis tincidunt, zombie slack-jawed gelida survival portenta. The unleashed virus est, et iam zombie mortui ambulabunt super terram. Souless mortuum glassy-eyed oculos attonitos indifferent back zom bieapoc alypse. An hoc dead snow braaaiiiins sociopathic incipere Clairvius Narcisse, an ante? Is bello mundi z?';